# Generated by Django 3.2.7 on 2021-09-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_created',
            new_name='completed',
        ),
    ]
